name: Deploy to PyPi

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build poetry
    - name: Build package
      run: poetry build
    - name: Publish python poetry package
      uses: JRubics/poetry-publish@v1.8
      with:
        # API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/)
        pypi_token: arst
