name: Deploy to PyPi

#on:
#  release:
#    types: [published]

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish python poetry package
      uses: JRubics/poetry-publish@v1.8
      with:
        pypi_token: ${ secrets.PYPI_TOKEN }
